keys_folder = "./public_keys/"
blocks_folder = "./blocks/"
pending_transactions_folder = "./pending/"
processed_transactions_folder = "./processed/"
wallet_skeleton = "./wallet_skeleton.py"
account_state_file_path = "./account_state.json"
